import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { BadgeCheck, ShieldCheck, TrendingUp, X } from 'lucide-react'
import { proofs } from '../data/proofs'

export default function ProofGallery() {
  const reduce = useReducedMotion()
  const [activeIndex, setActiveIndex] = useState(null)

  useEffect(() => {
    if (activeIndex === null) return undefined
    const handler = (event) => {
      if (event.key === 'Escape') setActiveIndex(null)
      if (event.key === 'ArrowRight') {
        setActiveIndex((index) => (index + 1) % proofs.length)
      }
      if (event.key === 'ArrowLeft') {
        setActiveIndex((index) => (index - 1 + proofs.length) % proofs.length)
      }
    }
    window.addEventListener('keydown', handler)
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => {
      window.removeEventListener('keydown', handler)
      document.body.style.overflow = previousOverflow
    }
  }, [activeIndex])

  const active = activeIndex !== null ? proofs[activeIndex] : null

  return (
    <section className="mt-16 sm:mt-20">
      <div className="mx-auto max-w-3xl text-center">
        <span className="chip mx-auto">
          <TrendingUp size={12} className="text-emerald-500" />
          <span>Student success showcase</span>
        </span>
        <h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">
          Real earnings. Real students.{' '}
          <span className="text-gradient-brand">Real proof.</span>
        </h2>
        <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300 sm:text-[15px]">
          Every screenshot below is a verified earning proof submitted by a
          student who applied the CPA MASTERY system. Tap any image to view the
          full size.
        </p>
        <div className="mt-4 flex flex-wrap justify-center gap-2 text-[12px] text-slate-500 dark:text-slate-400">
          <span className="chip">
            <BadgeCheck size={12} className="text-emerald-500" />
            <span>$15,000+ generated by students</span>
          </span>
          <span className="chip">
            <ShieldCheck size={12} className="text-cyan-500" />
            <span>Organic traffic methods only</span>
          </span>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.1 }}
        transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
        className="mt-10 grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4"
      >
        {proofs.map((proof, index) => (
          <motion.button
            type="button"
            key={proof.id}
            onClick={() => setActiveIndex(index)}
            whileHover={reduce ? undefined : { y: -3 }}
            whileTap={reduce ? undefined : { scale: 0.98 }}
            className="glass-card group relative overflow-hidden rounded-2xl p-0 outline-none ring-0 transition-shadow focus-visible:ring-2 focus-visible:ring-cyan-400/60"
            aria-label={`Open ${proof.label}`}
          >
            <div className="aspect-[9/16] w-full overflow-hidden bg-slate-900/5 dark:bg-slate-900/40">
              <img
                src={proof.src}
                alt={proof.label}
                loading="lazy"
                decoding="async"
                className="h-full w-full object-cover object-top transition-transform duration-500 group-hover:scale-[1.04]"
              />
            </div>
            <div className="pointer-events-none absolute inset-x-0 bottom-0 flex items-center justify-between gap-2 bg-gradient-to-t from-slate-950/80 via-slate-950/40 to-transparent px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100">
              <span className="flex items-center gap-1.5">
                <BadgeCheck size={12} className="text-emerald-300" />
                Verified proof
              </span>
              <span>#{String(index + 1).padStart(2, '0')}</span>
            </div>
          </motion.button>
        ))}
      </motion.div>

      <AnimatePresence>
        {active && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm"
            onClick={() => setActiveIndex(null)}
            role="dialog"
            aria-modal="true"
          >
            <motion.button
              type="button"
              onClick={() => setActiveIndex(null)}
              className="absolute right-4 top-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white transition-colors hover:bg-white/20"
              aria-label="Close preview"
            >
              <X size={20} />
            </motion.button>
            <motion.img
              key={active.id}
              initial={{ scale: 0.92, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.92, opacity: 0 }}
              transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
              src={active.src}
              alt={active.label}
              className="max-h-[88vh] max-w-full rounded-3xl shadow-[0_60px_120px_-30px_rgba(15,23,42,0.9)]"
              onClick={(event) => event.stopPropagation()}
            />
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  )
}
